[package]
name = "usartscreen"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt", "embassy-time-driver"] }
embassy-stm32 = { version = "0.6.0", features = ["defmt", "stm32f407vg", "time-driver-any", "memory-x"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-1_000_000"] }
embedded-hal-nb = "1.0.0"

defmt = "1.1.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
cortex-m = { version = "0.7.8", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
heapless = "0.9.3"
embassy-sync = "0.8.0"

[profile.dev]
lto = true
codegen-units = 1
debug = true

[profile.release]
debug = 2
